import { v4 as uuidv4 } from 'uuid'

interface ISubItem {
  id: string
  name: string
  url: string
}

interface IMainItem {
  [key: string]: {
    icon: string
    items: ISubItem[]
  }
}

const MenuItems: IMainItem = {
  Clothing: {
    icon: 'icon fa fa-shopping-bag',
    items: [
      { id: uuidv4(), name: 'Dresses', url: '#' },
      { id: uuidv4(), name: 'Shoes', url: '#' },
      { id: uuidv4(), name: 'Jackets', url: '#' },
      { id: uuidv4(), name: 'Sunglasses', url: '#' },
      { id: uuidv4(), name: 'Sport Wear', url: '#' },
      { id: uuidv4(), name: 'Blazers', url: '#' },
      { id: uuidv4(), name: 'Shirts', url: '#' },
      { id: uuidv4(), name: 'Shorts', url: '#' },
      { id: uuidv4(), name: 'Handbags', url: '#' },
      { id: uuidv4(), name: 'Jwellery', url: '#' },
      { id: uuidv4(), name: 'Swimwear', url: '#' },
      { id: uuidv4(), name: 'Tops', url: '#' },
      { id: uuidv4(), name: 'Flats', url: '#' },
      { id: uuidv4(), name: 'Shoes', url: '#' },
      { id: uuidv4(), name: 'Winter Wear', url: '#' },
      { id: uuidv4(), name: 'Night Suits', url: '#' },
      { id: uuidv4(), name: 'Toys & Games', url: '#' },
      { id: uuidv4(), name: 'Jeans', url: '#' },
      { id: uuidv4(), name: 'Shirts', url: '#' },
      { id: uuidv4(), name: 'Shoes', url: '#' },
      { id: uuidv4(), name: 'School Bags', url: '#' },
      { id: uuidv4(), name: 'Lunch Box', url: '#' },
      { id: uuidv4(), name: 'Footwear', url: '#' },
      { id: uuidv4(), name: 'Wipes', url: '#' },
      { id: uuidv4(), name: 'Sandals', url: '#' },
      { id: uuidv4(), name: 'Shorts', url: '#' },
      { id: uuidv4(), name: 'Dresses', url: '#' },
      { id: uuidv4(), name: 'Jwellery', url: '#' },
      { id: uuidv4(), name: 'Bags', url: '#' },
      { id: uuidv4(), name: 'Night Dress', url: '#' },
      { id: uuidv4(), name: 'Swim Wear', url: '#' },
      { id: uuidv4(), name: 'Toys', url: '#' },
    ],
  },
  Electronics: {
    icon: 'icon fa fa-laptop',
    items: [
      { id: uuidv4(), name: 'Gaming', url: '#' },
      { id: uuidv4(), name: 'Laptop Skins', url: '#' },
      { id: uuidv4(), name: 'Apple', url: '#' },
      { id: uuidv4(), name: 'Dell', url: '#' },
      { id: uuidv4(), name: 'Lenovo', url: '#' },
      { id: uuidv4(), name: 'Microsoft', url: '#' },
      { id: uuidv4(), name: 'Asus', url: '#' },
      { id: uuidv4(), name: 'Adapters', url: '#' },
      { id: uuidv4(), name: 'Batteries', url: '#' },
      { id: uuidv4(), name: 'Cooling Pads', url: '#' },
      { id: uuidv4(), name: 'Routers & Modems', url: '#' },
      { id: uuidv4(), name: 'CPUs, Processors', url: '#' },
      { id: uuidv4(), name: 'PC Gaming Store', url: '#' },
      { id: uuidv4(), name: 'Graphics Cards', url: '#' },
      { id: uuidv4(), name: 'Components', url: '#' },
      { id: uuidv4(), name: 'Webcam', url: '#' },
      { id: uuidv4(), name: 'Memory (RAM)', url: '#' },
      { id: uuidv4(), name: 'Motherboards', url: '#' },
      { id: uuidv4(), name: 'Keyboards', url: '#' },
      { id: uuidv4(), name: 'Headphones', url: '#' },
    ],
  },
  Shoes: {
    icon: 'icon fa fa-paw',
    items: [
      { id: uuidv4(), name: 'Dresses', url: '#' },
      { id: uuidv4(), name: 'Shoes', url: '#' },
      { id: uuidv4(), name: 'Jackets', url: '#' },
      { id: uuidv4(), name: 'Sunglasses', url: '#' },
      { id: uuidv4(), name: 'Sport Wear', url: '#' },
      { id: uuidv4(), name: 'Blazers', url: '#' },
      { id: uuidv4(), name: 'Shirts', url: '#' },
      { id: uuidv4(), name: 'Shorts', url: '#' },
      { id: uuidv4(), name: 'Handbags', url: '#' },
      { id: uuidv4(), name: 'Jwellery', url: '#' },
      { id: uuidv4(), name: 'Swimwear', url: '#' },
      { id: uuidv4(), name: 'Tops', url: '#' },
      { id: uuidv4(), name: 'Flats', url: '#' },
      { id: uuidv4(), name: 'Shoes', url: '#' },
      { id: uuidv4(), name: 'Winter Wear', url: '#' },
      { id: uuidv4(), name: 'Night Suits', url: '#' },
      { id: uuidv4(), name: 'Toys & Games', url: '#' },
      { id: uuidv4(), name: 'Jeans', url: '#' },
      { id: uuidv4(), name: 'Shirts', url: '#' },
      { id: uuidv4(), name: 'Shoes', url: '#' },
      { id: uuidv4(), name: 'School Bags', url: '#' },
      { id: uuidv4(), name: 'Lunch Box', url: '#' },
      { id: uuidv4(), name: 'Footwear', url: '#' },
      { id: uuidv4(), name: 'Wipes', url: '#' },
      { id: uuidv4(), name: 'Sandals', url: '#' },
      { id: uuidv4(), name: 'Shorts', url: '#' },
      { id: uuidv4(), name: 'Dresses', url: '#' },
      { id: uuidv4(), name: 'Jwellery', url: '#' },
      { id: uuidv4(), name: 'Bags', url: '#' },
      { id: uuidv4(), name: 'Night Dress', url: '#' },
      { id: uuidv4(), name: 'Swim Wear', url: '#' },
      { id: uuidv4(), name: 'Toys', url: '#' },
    ],
  },
  Watches: {
    icon: 'icon fa fa-clock-o',
    items: [
      { id: uuidv4(), name: 'Gaming', url: '#' },
      { id: uuidv4(), name: 'Laptop Skins', url: '#' },
      { id: uuidv4(), name: 'Apple', url: '#' },
      { id: uuidv4(), name: 'Dell', url: '#' },
      { id: uuidv4(), name: 'Lenovo', url: '#' },
      { id: uuidv4(), name: 'Microsoft', url: '#' },
      { id: uuidv4(), name: 'Asus', url: '#' },
      { id: uuidv4(), name: 'Adapters', url: '#' },
      { id: uuidv4(), name: 'Batteries', url: '#' },
      { id: uuidv4(), name: 'Cooling Pads', url: '#' },
      { id: uuidv4(), name: 'Routers & Modems', url: '#' },
      { id: uuidv4(), name: 'CPUs, Processors', url: '#' },
      { id: uuidv4(), name: 'PC Gaming Store', url: '#' },
      { id: uuidv4(), name: 'Graphics Cards', url: '#' },
      { id: uuidv4(), name: 'Components', url: '#' },
      { id: uuidv4(), name: 'Webcam', url: '#' },
      { id: uuidv4(), name: 'Memory (RAM)', url: '#' },
      { id: uuidv4(), name: 'Motherboards', url: '#' },
      { id: uuidv4(), name: 'Keyboards', url: '#' },
      { id: uuidv4(), name: 'Headphones', url: '#' },
    ],
  },
  Jewellery: {
    icon: 'icon fa fa-diamond',
    items: [
      { id: uuidv4(), name: 'Dresses', url: '#' },
      { id: uuidv4(), name: 'Shoes', url: '#' },
      { id: uuidv4(), name: 'Jackets', url: '#' },
      { id: uuidv4(), name: 'Sunglasses', url: '#' },
      { id: uuidv4(), name: 'Sport Wear', url: '#' },
      { id: uuidv4(), name: 'Blazers', url: '#' },
      { id: uuidv4(), name: 'Shirts', url: '#' },
      { id: uuidv4(), name: 'Shorts', url: '#' },
      { id: uuidv4(), name: 'Handbags', url: '#' },
      { id: uuidv4(), name: 'Jwellery', url: '#' },
      { id: uuidv4(), name: 'Swimwear', url: '#' },
      { id: uuidv4(), name: 'Tops', url: '#' },
      { id: uuidv4(), name: 'Flats', url: '#' },
      { id: uuidv4(), name: 'Shoes', url: '#' },
      { id: uuidv4(), name: 'Winter Wear', url: '#' },
      { id: uuidv4(), name: 'Night Suits', url: '#' },
      { id: uuidv4(), name: 'Toys & Games', url: '#' },
      { id: uuidv4(), name: 'Jeans', url: '#' },
      { id: uuidv4(), name: 'Shirts', url: '#' },
      { id: uuidv4(), name: 'Shoes', url: '#' },
      { id: uuidv4(), name: 'School Bags', url: '#' },
      { id: uuidv4(), name: 'Lunch Box', url: '#' },
      { id: uuidv4(), name: 'Footwear', url: '#' },
      { id: uuidv4(), name: 'Wipes', url: '#' },
      { id: uuidv4(), name: 'Sandals', url: '#' },
      { id: uuidv4(), name: 'Shorts', url: '#' },
      { id: uuidv4(), name: 'Dresses', url: '#' },
      { id: uuidv4(), name: 'Jwellery', url: '#' },
      { id: uuidv4(), name: 'Bags', url: '#' },
      { id: uuidv4(), name: 'Night Dress', url: '#' },
      { id: uuidv4(), name: 'Swim Wear', url: '#' },
      { id: uuidv4(), name: 'Toys', url: '#' },
    ],
  },
  'Health and Beauty': {
    icon: 'icon fa fa-heartbeat',
    items: [
      { id: uuidv4(), name: 'Gaming', url: '#' },
      { id: uuidv4(), name: 'Laptop Skins', url: '#' },
      { id: uuidv4(), name: 'Apple', url: '#' },
      { id: uuidv4(), name: 'Dell', url: '#' },
      { id: uuidv4(), name: 'Lenovo', url: '#' },
      { id: uuidv4(), name: 'Microsoft', url: '#' },
      { id: uuidv4(), name: 'Asus', url: '#' },
      { id: uuidv4(), name: 'Adapters', url: '#' },
      { id: uuidv4(), name: 'Batteries', url: '#' },
      { id: uuidv4(), name: 'Cooling Pads', url: '#' },
      { id: uuidv4(), name: 'Routers & Modems', url: '#' },
      { id: uuidv4(), name: 'CPUs, Processors', url: '#' },
      { id: uuidv4(), name: 'PC Gaming Store', url: '#' },
      { id: uuidv4(), name: 'Graphics Cards', url: '#' },
      { id: uuidv4(), name: 'Components', url: '#' },
      { id: uuidv4(), name: 'Webcam', url: '#' },
      { id: uuidv4(), name: 'Memory (RAM)', url: '#' },
      { id: uuidv4(), name: 'Motherboards', url: '#' },
      { id: uuidv4(), name: 'Keyboards', url: '#' },
      { id: uuidv4(), name: 'Headphones', url: '#' },
    ],
  },
  'Kids and Babies': {
    icon: 'icon fa fa-paper-plane',
    items: [],
  },
  Sports: {
    icon: 'icon fa fa-futbol-o',
    items: [],
  },
  'Home and Garden': {
    icon: 'icon fa fa-envira',
    items: [],
  },
}

export default MenuItems
